using System;

namespace GameLib
{
    public enum EnumValueType
    {
        VALUE_TYPE_FREE,
        VALUE_TYPE_MIN,
        VALUE_TYPE_MAX,
    }

    public enum EnumSkillConst
    {
        SKILL_GRADE_COUNT = 3,
        SKILL_EFFECT_COUNT = 4,
        SKILL_GRADE_STEP_COUNT = 20,
        SKILL_GRADEGAP = 25,
    }

    public enum EnumSkillType : byte
    {
        SKILL_TYPE_NONE,
        SKILL_TYPE_ACTIVE,
        SKILL_TYPE_SUPPORT,
        SKILL_TYPE_GUILD,
        SKILL_TYPE_HORSE,
        SKILL_TYPE_MAX_NUM,
    }

    public enum EnumSkillTableTokenType
    {

        TABLE_TOKEN_TYPE_VNUM,
        TABLE_TOKEN_TYPE_MAX_LEVEL,
        TABLE_TOKEN_TYPE_LEVEL_LIMIT,
        TABLE_TOKEN_TYPE_POINT_POLY,
        TABLE_TOKEN_TYPE_SP_COST_POLY,
        TABLE_TOKEN_TYPE_DURATION_POLY,
        TABLE_TOKEN_TYPE_DURATION_SP_COST_POLY,
        TABLE_TOKEN_TYPE_COOLDOWN_POLY,
        TABLE_TOKEN_TYPE_TARGET_RANGE,
        TABLE_TOKEN_TYPE_MAX_NUM,
        /*
        TABLE_TOKEN_TYPE_VNUM,
        TABLE_TOKEN_TYPE_NAME,
        TABLE_TOKEN_TYPE_TYPE,
        TABLE_TOKEN_TYPE_LEVEL_STEP,
        TABLE_TOKEN_TYPE_MAX_LEVEL,
        TABLE_TOKEN_TYPE_LEVEL_LIMIT,
        TABLE_TOKEN_TYPE_POINT_ON,
        TABLE_TOKEN_TYPE_POINT_POLY,
        TABLE_TOKEN_TYPE_SP_COST_POLY,
        TABLE_TOKEN_TYPE_DURATION_POLY,
        TABLE_TOKEN_TYPE_DURATION_SP_COST_POLY,
        TABLE_TOKEN_TYPE_COOLDOWN_POLY,
        TABLE_TOKEN_TYPE_MASTER_BONUS_POLY,
        TABLE_TOKEN_TYPE_ATTACK_GRADE_POLY,
        TABLE_TOKEN_TYPE_FLAG,
        TABLE_TOKEN_TYPE_AFFECT_FLAG,
        TABLE_TOKEN_TYPE_POINT_ON2,
        TABLE_TOKEN_TYPE_POINT_POLY2,
        TABLE_TOKEN_TYPE_DURATION_POLY2,
        TABLE_TOKEN_TYPE_AFFECT_FLAG2,
        TABLE_TOKEN_TYPE_PREREQUISITE_SKILL_VNUM,
        TABLE_TOKEN_TYPE_PREREQUISITE_SKILL_LEVEL,
        TABLE_TOKEN_TYPE_SKILL_TYPE,
        TABLE_TOKEN_TYPE_MAX_HIT,
        TABLE_TOKEN_TYPE_SPLASH_AROUND_DAMAGE_ADJUST_POLY,
        TABLE_TOKEN_TYPE_TARGET_RANGE,
        TABLE_TOKEN_TYPE_SPLASH_RANGE,
        TABLE_TOKEN_TYPE_MAX_NUM,
        */
    }

    [Flags]
    public enum EnumSkillAttribute
    {
        SKILL_ATTRIBUTE_NEED_TARGET = (1 << 0),
        SKILL_ATTRIBUTE_TOGGLE = (1 << 1),
        SKILL_ATTRIBUTE_WEAPON_LIMITATION = (1 << 2),
        SKILL_ATTRIBUTE_MELEE_ATTACK = (1 << 3),
        SKILL_ATTRIBUTE_USE_HP = (1 << 4),
        SKILL_ATTRIBUTE_CAN_CHANGE_DIRECTION = (1 << 5),
        SKILL_ATTRIBUTE_STANDING_SKILL = (1 << 6),
        SKILL_ATTRIBUTE_ONLY_FOR_ALLIANCE = (1 << 7),
        SKILL_ATTRIBUTE_CAN_USE_FOR_ME = (1 << 8),
        SKILL_ATTRIBUTE_NEED_CORPSE = (1 << 9),
        SKILL_ATTRIBUTE_FAN_RANGE = (1 << 10),
        SKILL_ATTRIBUTE_CAN_USE_IF_NOT_ENOUGH = (1 << 11),
        SKILL_ATTRIBUTE_NEED_EMPTY_BOTTLE = (1 << 12),
        SKILL_ATTRIBUTE_NEED_POISON_BOTTLE = (1 << 13),
        SKILL_ATTRIBUTE_ATTACK_SKILL = (1 << 14),
        SKILL_ATTRIBUTE_TIME_INCREASE_SKILL = (1 << 15),
        SKILL_ATTRIBUTE_CHARGE_ATTACK = (1 << 16),
        SKILL_ATTRIBUTE_PASSIVE = (1 << 17),
        SKILL_ATTRIBUTE_CANNOT_LEVEL_UP = (1 << 18),
        SKILL_ATTRIBUTE_ONLY_FOR_GUILD_WAR = (1 << 19),
        SKILL_ATTRIBUTE_MOVING_SKILL = (1 << 20),
        SKILL_ATTRIBUTE_HORSE_SKILL = (1 << 21),
        SKILL_ATTRIBUTE_CIRCLE_RANGE = (1 << 22),
        SKILL_ATTRIBUTE_SEARCH_TARGET = (1 << 23),
    }

    [Flags]
    public enum EnumSkillNeedWeapon
    {
        SKILL_NEED_WEAPON_SWORD = (1 << EnumWeaponSubTypes.WEAPON_SWORD),
        SKILL_NEED_WEAPON_DAGGER = (1 << EnumWeaponSubTypes.WEAPON_DAGGER),
        SKILL_NEED_WEAPON_BOW = (1 << EnumWeaponSubTypes.WEAPON_BOW),
        SKILL_NEED_WEAPON_TWO_HANDED = (1 << EnumWeaponSubTypes.WEAPON_TWO_HANDED),
        SKILL_NEED_WEAPON_DOUBLE_SWORD = (1 << EnumWeaponSubTypes.WEAPON_DAGGER),
        SKILL_NEED_WEAPON_BELL = (1 << EnumWeaponSubTypes.WEAPON_BELL),
        SKILL_NEED_WEAPON_FAN = (1 << EnumWeaponSubTypes.WEAPON_FAN),
        SKILL_NEED_WEAPON_ARROW = (1 << EnumWeaponSubTypes.WEAPON_ARROW),
        SKILL_NEED_WEAPON_MOUNT_SPEAR = (1 << EnumWeaponSubTypes.WEAPON_MOUNT_SPEAR),
        SKILL_NEED_WEAPON_CLAW = (1 << EnumWeaponSubTypes.WEAPON_CLAW),
        SKILL_NEED_WEAPON_EMPTY_HAND = (1 << EnumWeaponSubTypes.WEAPON_NONE),
    }
}